[build]
builder = "NIXPACKS"

[deploy]
startCommand = "python manage.py migrate && gunicorn finsage_project.wsgi:application --bind 0.0.0.0:$PORT"
healthcheckPath = "/health/"
healthcheckTimeout = 300
healthcheckInterval = 30
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environments.production]
